### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by prologic** [oragono/oragono-docker#1]
Document how to use this new Docker image and the Stackfile (`docker-composeyml`)

**Comment by shahzeb1** [comment]
Is this still an open issue?

I'm down to work on this as a PR.

**Comment by DanielOaks** [comment]
Hey @shahzeb1, definitely! Honestly I'm a bit unfamiliar with docker and all, so I'm totally down for any assistance with this repo :)

**Comment by DanielOaks** [comment]
Awesome, now updated thanks to @csmith!
