### ISSUE TITLE
Dockerfile no longer builds

### ISSUE THREAD

**Issue by csmith** [oragono/oragono-docker#13]
```
Step 13/30 : RUN make build
 ---> Running in af9395fcb7ef
make: *** No rule to make target 'build'.  Stop.
Removing intermediate container af9395fcb7ef
The command '/bin/sh -c make build' returned a non-zero code: 2
```

Looks like the build target went away in https://github.com/oragono/oragono/commit/b6feca05a335852142b1fb41cafeb2a1ec4a05db

@slingamn what target should this be using now? or should the dockerfile just call `goreleaser --snapshot --rm-dist`?

**Comment by slingamn** [comment]
The default target of the Makefile is still `all`, which now invokes `install`, so I think you can just replace `make build` with `make`? The binary will end up in a different place, though: `${GOPATH}/bin/oragono`.

goreleaser is no longer required, so you can remove any references to it.

Sorry about this, let me know if you need anything.
