### ISSUE TITLE
Version tags to test older version?

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono-docker#18]
I am facing this strange issue that with both the `latest` and the `dev` tag the connection to my Oragono server has become really un-stable. Maybe 1 in 3 connection attempts work and then I am kicked out again after a short while.

I don't think this happened with the Docker image from a few weeks ago (and my server is otherwise more or less unchanged), but because there are no version tags I can not go back to an older version of the Docker image either.

It also doesn't happen on the irc.darwin.network v1.2.0rc1 server, so it must be something with my specific Docker-based setup, or a recent change in the way these Docker images are made?

Help appreciated as I am really a bit stumped and have no idea what to try next.

Having older versions of the Docker image on Dockerhub would have certainly helped though :)

Edit: To clarify: I don't think it is an actual issue with Oragono... just something is borked on my end and it would be nice if  could go back to an older version to rule out some potential issues.

**Comment by poVoq** [comment]
Hmm, could it be that the switch to TLS1.3 is causing the strange unstable connection issues I see when running the Docker image?

Connecting via The Lounge IRC client for example is almost impossible, maybe 1 in 10 connection attempts work.

With a regular client I get kicked out regularly also for some reason.

The in client errors make me guess it is a TLS handshake issue (Dispatch `Error: tls: DialWithDialer timed out`)

**Comment by slingamn** [comment]
Interesting, yeah, that's a real possibility.

Come find us in #oragono on Freenode. There's a few different things we can investigate. In particular, you could try adding this line to `run.sh` before the final exec:

````bash
export GODEBUG=tls13=0
````

and then rebuild the image.

**Comment by slingamn** [comment]
Also, try connecting your Lounge instance to my stage server at files.stronghold.network, TLS on port 6697. It's running vanilla 1.2.0 built with go 1.13.4 and is TLS 1.3-capable.

**Comment by poVoq** [comment]
Similar behaviour with `files.stronghold.network` for me.
Connecting with The Lounge client it seems to make the initial connection a more reliably, but within less than a minute the collection is lost again.

Edit: hmm, with other clients your server seems much more stable though.

**Comment by slingamn** [comment]
From my side, I see your client sending actual QUIT lines:

````
2019-11-17T21:24:03.009Z : debug : userinput : poVoq : <-  : QUIT :FreeGameDev - https://irc.freegamedev.net
2019-11-17T21:24:03.009Z : info : localconnect-ip : disconnecting session of poVoq from [redacted]
2019-11-17T21:24:03.009Z : debug : quit : poVoq is no longer on the server
````

**Comment by poVoq** [comment]
Ok closing this. The Docker image of ngircd has exactly the same behaviour on my Docker based setup. Absolutely no idea what is causing this as other services such as XMPP work perfectly fine.

**Comment by slingamn** [comment]
Just a thought: XMPP is probably more tolerant of disconnections and reconnections. The reliance of IRC on long-running TCP connections is one of its main weaknesses --- we're working to address this with the [CHATHISTORY](https://github.com/ircv3/ircv3-specifications/pull/393/) and [oragono.io/bnc](https://oragono.io/bnc) specifications.
