### ISSUE TITLE
Datastore should be in volume

### ISSUE THREAD

**Issue by csmith** [oragono/oragono-docker#6]
In order to persist it properly, oragono's database should be stored on a volume defined in the Dockerfile. At the minute it's just stored in the working directory, so will be lost if the container is retstarted, upgraded, etc.

Couple of sticking points:

- The database path is specified in the config, and the default config gives a relative path (ideally it'd sit in its own folder, so docker can mount a volume there)
- It needs to be initialised before use, which makes for some fiddly manual action. At the moment the docker image will try to initialise a database if it doesn't exist in the working directory regardless of what the config says.

**Comment by DanielOaks** [comment]
Definitely, this makes sense. Back when this repo was started I knew next to nothing about docker so didn't even cross my mind. These days I know a liiittle more so makes sense to do it.

Question is, should we throw the config file in the volume as well? Let the config file, db, TLS certs and all sit alongside it and all.

**Comment by DanielOaks** [comment]
This should be getting done now with the config file, data store, and certificates stored in the volume mount. Also generates a new oper password on first creating the config file.
