### ISSUE TITLE
build stable instead of master once v0.13.0 is released

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono-docker#8]
Once https://github.com/oragono/oragono/commit/6667585605d8557c83bdf9f0048d2a33d9fa0de0 is in the stable branch (with v0.13.0), build stable instead of master.

**Comment by DanielOaks** [comment]
Yeah definitely, so how this works is that `master` in this repo builds to the `:dev` tag on Dockerhub. The branch `stable` in this repo builds to `:latest`, so that people who grab the default from Dockerhub always grab the stable build first.

**Comment by DanielOaks** [comment]
Now building `v1.0.0-rc1`
